---
  - hosts: all
    become: true
    tasks:
        - name: ensure that services are running
          service:
              name: "{{ process_name }}"
              state: started
              enabled: yes
