---
  - hosts: all
    become: true
    pre_tasks:
        - name: Gathering ec2 facts
          action: ec2_metadata_facts
        - name: Instance De-register
          become: False
          local_action:
            module: ec2_elb
            region: us-east-1
            instance_id: "{{ ansible_ec2_instance_id }}"
            state: absent
            wait_timeout: 120
    tasks:
        - name: sleep for 120 seconds and continue with play
          become: True
          wait_for: 
            timeout=120
        - name: Restarting apache2
          become: True
          service:
              name: apache2
              state: restarted
              enabled: yes
    post_tasks:
        - name: Instance Register
          become: False
          local_action:
            module: ec2_elb
            region: us-east-1
            instance_id: "{{ ansible_ec2_instance_id }}"
            ec2_elbs: "{{ item }}"
            state: present
          with_items: "{{ ec2_elbs }}"
...
