---
  - hosts: all
    become: true
    tasks:
        - name: Restarting plivocomm
          shell: plivocomm restart
        - name: Restarting freeswitch
          shell: systemctl restart freeswitch
        - name: Checking number of channels
          shell: /usr/local/freeswitch/bin/fs_cli -b -q -H 127.0.0.1 -P 8058 -p b1nladen -x 'show channels'
          register: shell_result
        - debug: msg= "{{ shell_result.stdout }}
...
