---
  - hosts: all
    become: true
    tasks:
        - name: Restarting plivocomm
          shell: plivocomm restart
        - name: Restarting freeswitch
          shell: systemctl restart freeswitch
        - name: Waiting for FS to restart (10s)..
          become: True
          wait_for: 
           timeout=10
        - name: Checking number of channels
          shell: /usr/local/freeswitch/bin/fs_cli -b -q -H 127.0.0.1 -P 8058 -p b1nladen -x 'show channels'
          executable: /bin/zsh
          register: shell_result
          ignore_errors: True
        - debug: 
            var: shell_result.stdout
...
