---
- hosts: all
  become: true
  vars:
    users:
    - "siby"
  tasks:
  - name: "Create user accounts"
    user:
      name: "{{ item }}"
      shell: /bin/bash
      groups: "root"
    with_items: "{{ users }}"
  - name: "Add authorized keys"
    authorized_key:
      user: "{{ item }}"
      key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
    with_items: "{{ users }}"
  - name: "Allow admin users to sudo without a password"
    lineinfile:
      dest: "/etc/sudoers" # path: in version 2.3
      state: "present"
      regexp: "^%root"
      line: "%root ALL=(ALL) NOPASSWD: ALL"
...
