---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Create IAM Managed Policy
    iam_managed_policy:
    aws_access_key:""
    aws_secret_key:""
    policy_name: "ManagedPolicy-testing"
      policy: '{"Version": "2012-10-17", "Statement": [{"Action": [ "lex:GetBot", "lex:GetBotAlias", "lex:GetBotAliases", "lex:GetBots", "lex:GetBotChannelAssociation", "lex:GetBotChannelAssociations", "lex:GetBotVersions", "lex:GetBuiltinIntent", "lex:GetBuiltinIntents", "lex:GetBuiltinSlotTypes", "lex:GetIntent", "lex:GetIntents", "lex:GetIntentVersions", "lex:GetSlotType", "lex:GetSlotTypes", "lex:GetSlotTypeVersions", "lex:GetUtterancesView"], "Effect": "Allow", "Resource": "*"}]}'
      only_version: true
      state: present
...
